### ISSUE TITLE
Clean all the unnecessary codes & floders

### ISSUE THREAD

**Issue by syket-das** [NH-labs-Agency/agency#1]
This repo is having many un necessary folders even codes. 
Those should be removed from the repo.

Suggestion:
Go through the whole repo
Look for the files which is not necessary, find if that file is rendering in somewhere in the webpage or not.
If it 's not delete the file.

We Just need the homepage code.
If any code is not realated to homepage or file delete it.

Caution: After deletion of any code or file try running the website if it breaks or not.

**Comment by Ekep-Obasi** [comment]
@syket-das do I have permissions to push here 

![Screenshot from 2024-10-05 08-54-07](https://github.com/user-attachments/assets/129516b3-fb5b-4ec0-9c5e-8ba9bcbbbf10)

**Comment by syket-das** [comment]
Yess you can,

**Comment by syket-das** [comment]
@FayeKelmith take a look

**Comment by FayeKelmith** [comment]
yes, ma man. you can push.
